/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Analisis;

import javax.swing.JOptionPane;

/**
 *
 * @author AREVALO GONZALEZ
 */
public class EcuacionSegundoGrado extends javax.swing.JFrame {
     Operaciones operacion = new Operaciones();
     General menu = new General();
    /**
     * Creates new form EcuacionSegundoGrado
     */
    
    public EcuacionSegundoGrado() {
        initComponents();
        btnNo.setVisible(false);
        txtDecimal.setVisible(false);
        btnCalcular.setVisible(false);
        this.setLocationRelativeTo(null);
        setResizable(false);
        btnFinal.setVisible(false);
        lblx1.setVisible(false);
        lblx2.setVisible(false);
        txtRaiz1.setVisible(false);
        txtRaiz2.setVisible(false);
        lblValorCal.setVisible(false);
        txtRaizCal1.setVisible(false);
        txtRaizCal2.setVisible(false);
        txtEa.setVisible(false);
        lblEa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblfuncion = new javax.swing.JLabel();
        lblvalor = new javax.swing.JLabel();
        lblc = new javax.swing.JLabel();
        lbla = new javax.swing.JLabel();
        lblb = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        txtCoeCuadrado = new javax.swing.JTextField();
        txtCoeLineal = new javax.swing.JTextField();
        txtIndependiente = new javax.swing.JTextField();
        txtDecimal = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnFinal = new javax.swing.JButton();
        lblx1 = new javax.swing.JLabel();
        txtRaiz1 = new javax.swing.JTextField();
        txtRaiz2 = new javax.swing.JTextField();
        lblx2 = new javax.swing.JLabel();
        lblValorCal = new javax.swing.JLabel();
        txtRaizCal1 = new javax.swing.JTextField();
        txtRaizCal2 = new javax.swing.JTextField();
        lblEa = new javax.swing.JLabel();
        txtEa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(250, 200));
        setName("EcuacionCuadratica"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblfuncion.setText("Sea una ecuacion de tipo ax²+bx +c ");
        getContentPane().add(lblfuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lblvalor.setText("que valor les darias a los coeficientes ?");
        getContentPane().add(lblvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        lblc.setText("c:");
        getContentPane().add(lblc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        lbla.setText("a:");
        getContentPane().add(lbla, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        lblb.setText("b:");
        getContentPane().add(lblb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        btnNext.setText("Listo");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 70, 20));

        btnNo.setText("Cancelar");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 90, -1));

        txtCoeCuadrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoeCuadradoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCoeCuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 30, -1));

        txtCoeLineal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoeLinealKeyTyped(evt);
            }
        });
        getContentPane().add(txtCoeLineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 30, -1));

        txtIndependiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIndependienteKeyTyped(evt);
            }
        });
        getContentPane().add(txtIndependiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 30, -1));

        txtDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDecimalActionPerformed(evt);
            }
        });
        txtDecimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDecimalKeyTyped(evt);
            }
        });
        getContentPane().add(txtDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 70, -1));

        btnCalcular.setText("Calcular ");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 90, -1));

        btnFinal.setText("Finalizar");
        btnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 90, -1));

        lblx1.setText("X1 =");
        getContentPane().add(lblx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, 20));

        txtRaiz1.setEditable(false);
        getContentPane().add(txtRaiz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 60, -1));

        txtRaiz2.setEditable(false);
        getContentPane().add(txtRaiz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 60, -1));

        lblx2.setText("X2 =");
        getContentPane().add(lblx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, 20));

        lblValorCal.setText("Valores calculados");
        getContentPane().add(lblValorCal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        txtRaizCal1.setEditable(false);
        getContentPane().add(txtRaizCal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 80, -1));

        txtRaizCal2.setEditable(false);
        getContentPane().add(txtRaizCal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 80, -1));

        lblEa.setText("Ea =");
        getContentPane().add(lblEa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        txtEa.setEditable(false);
        getContentPane().add(txtEa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       String cadena="";
        if (!txtCoeCuadrado.getText().equals("")){
          if (!txtCoeLineal.getText().equals("")){
            if (!txtIndependiente.getText().equals("")){
            cadena=operacion.Validacion(Integer.parseInt(txtCoeCuadrado.getText()),
                    Integer.parseInt(txtCoeLineal.getText()),Integer.parseInt(txtIndependiente.getText()));
               lblvalor.setVisible(false);
               lblfuncion.setText("Cuantos decimales?");
               txtDecimal.setVisible(true);
               btnNo.setVisible(false);
               btnCalcular.setVisible(true);
               lbla.setVisible(false);
               lblb.setVisible(false);
               lblc.setVisible(false);
                btnNo.setVisible(true);
                btnNext.setVisible(false);
                txtCoeCuadrado.setVisible(false);
                txtCoeLineal.setVisible(false);
                txtIndependiente.setVisible(false);
           }else{
                JOptionPane.showMessageDialog(null, "ingresa un valor en \nel termino independiente");
                txtIndependiente.setRequestFocusEnabled(true);
            }
          }else{
              JOptionPane.showMessageDialog(null, "ingresa un valor en \nel coeficiente lineal");
                txtIndependiente.setRequestFocusEnabled(true);
          }   
        }else{
            JOptionPane.showMessageDialog(null, "ingresa un valor en \nel coeficiente cuadratico");
                txtIndependiente.setRequestFocusEnabled(true);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
btnNext.setVisible(true);
btnNo.setVisible(false);
lblvalor.setVisible(true);
lblfuncion.setVisible(true);
lbla.setVisible(true);
lblb.setVisible(true);
lblc.setVisible(true);
txtCoeCuadrado.setVisible(true);
txtCoeLineal.setVisible(true);
txtIndependiente.setVisible(true);
txtCoeCuadrado.setText("");
txtCoeCuadrado.setRequestFocusEnabled(true);
txtCoeLineal.setText("");
txtIndependiente.setText("");
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if(!txtDecimal.getText().equals("")&& Integer.parseInt(txtDecimal.getText())<15){
            double PrimeraRaiz,SegundaRaiz;
        PrimeraRaiz=operacion.RaicesMetodo1(Integer.parseInt(txtCoeCuadrado.getText()), 
                Integer.parseInt(txtCoeLineal.getText()),Integer.parseInt(txtIndependiente.getText()),1);
        SegundaRaiz=operacion.RaicesMetodo1(Integer.parseInt(txtCoeCuadrado.getText()), 
                Integer.parseInt(txtCoeLineal.getText()),Integer.parseInt(txtIndependiente.getText()),2);
        System.out.println(""+PrimeraRaiz);
        System.out.println(""+SegundaRaiz);
        if (PrimeraRaiz ==0 || SegundaRaiz==0){
          JOptionPane.showMessageDialog(null, "Tiene Raices Imaginarias");
          this.setVisible(false);
          menu.setVisible(true);  
        }else{
            txtRaiz1.setText(""+PrimeraRaiz);
            txtRaiz2.setText(""+SegundaRaiz);
        }
      btnCalcular.setVisible(false);
      btnFinal.setVisible(true);
      btnNo.setVisible(false);
     txtDecimal.setVisible(false);
     lblfuncion.setVisible(false);
     lblvalor.setVisible(true);
     lblvalor.setText("Valores reales");             
      lblx2.setVisible(true);
      lblx1.setVisible(true);
      txtRaiz1.setVisible(true);
      txtRaiz2.setVisible(true);
      lblValorCal.setVisible(true);
      txtRaizCal1.setVisible(true);
      txtRaizCal2.setVisible(true);
      txtEa.setVisible(true);
      lblEa.setVisible(true);
        }else{
            if(txtDecimal.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese con cuantos decimales");
            }else{
                JOptionPane.showMessageDialog(null, "Demaciados numeros Decimales");
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtDecimalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDecimalKeyTyped
        char c =evt.getKeyChar();
        if(c<'0' || c>'9' ){
            evt.consume();
        }
    }//GEN-LAST:event_txtDecimalKeyTyped

    private void txtCoeCuadradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoeCuadradoKeyTyped
       char c =evt.getKeyChar();
        if(c!='-'&&(c<'0' || c>'9') ){
            evt.consume();
        }
    }//GEN-LAST:event_txtCoeCuadradoKeyTyped

    private void txtCoeLinealKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoeLinealKeyTyped
        char c =evt.getKeyChar();
        if(c!='-'&&(c<'0' || c>'9') ){
            evt.consume();
        }
    }//GEN-LAST:event_txtCoeLinealKeyTyped

    private void txtIndependienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIndependienteKeyTyped
        char c =evt.getKeyChar();
        if(c!='-'&&(c<'0' || c>'9') ){
            evt.consume();
        }
    }//GEN-LAST:event_txtIndependienteKeyTyped

    private void txtDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDecimalActionPerformed
        
    }//GEN-LAST:event_txtDecimalActionPerformed

    private void btnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalActionPerformed
        General menu =new General();
        menu.show();
        this.setVisible(false);
    }//GEN-LAST:event_btnFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcuacionSegundoGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcuacionSegundoGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcuacionSegundoGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcuacionSegundoGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcuacionSegundoGrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnFinal;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNo;
    private javax.swing.JLabel lblEa;
    private javax.swing.JLabel lblValorCal;
    private javax.swing.JLabel lbla;
    private javax.swing.JLabel lblb;
    private javax.swing.JLabel lblc;
    private javax.swing.JLabel lblfuncion;
    private javax.swing.JLabel lblvalor;
    private javax.swing.JLabel lblx1;
    private javax.swing.JLabel lblx2;
    private javax.swing.JTextField txtCoeCuadrado;
    private javax.swing.JTextField txtCoeLineal;
    private javax.swing.JTextField txtDecimal;
    private javax.swing.JTextField txtEa;
    private javax.swing.JTextField txtIndependiente;
    private javax.swing.JTextField txtRaiz1;
    private javax.swing.JTextField txtRaiz2;
    private javax.swing.JTextField txtRaizCal1;
    private javax.swing.JTextField txtRaizCal2;
    // End of variables declaration//GEN-END:variables
}
