/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Analisis;

/**
 *
 * @author AREVALO GONZALEZ
 */
public class General extends javax.swing.JFrame {

    /**
     * Creates new form General
     */
    public General() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAritmetica = new javax.swing.JButton();
        btnTrigon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnExpon = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAritmetica.setText("Funcion Aritmetica");
        btnAritmetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAritmeticaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAritmetica, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        btnTrigon.setText("Funcion Trigonometrica");
        btnTrigon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrigonActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrigon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel1.setText("Solucion a los ejercicios propuestos ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnExpon.setText("Funcion Exponencial");
        getContentPane().add(btnExpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 160, -1));

        btnSalir.setBackground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("X");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 50, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAritmeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAritmeticaActionPerformed
        EcuacionSegundoGrado ec= new EcuacionSegundoGrado();
        ec.show();
        this.setVisible(false);
    }//GEN-LAST:event_btnAritmeticaActionPerformed

    private void btnTrigonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrigonActionPerformed
        SerieCosx sc=new SerieCosx();
        sc.show();
        this.setVisible(false);
    }//GEN-LAST:event_btnTrigonActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new General().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAritmetica;
    private javax.swing.JButton btnExpon;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTrigon;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
